import { StyleSheet } from 'react-native';
import Colors from '../../helpers/Colors';

const styles = StyleSheet.create({
  contentContainer: {
    paddingTop: 10
  },
  ingredientsContainer: {
    alignSelf: 'stretch',
    backgroundColor: '#ffffff',
    margin: 10,
    borderRadius:10,
    marginTop:5,
    shadowColor: Colors.black,
    shadowOffset: { width: 1, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 2,
  },
  cardContainer: {
    alignSelf: 'stretch',
    backgroundColor: '#ffffff',
    margin: 10,
    marginBottom:40,
    borderRadius:10,
    marginTop:5,
    shadowColor: Colors.black,
    shadowOffset: { width: 1, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 2,
  },
  searchInput: {
    height: 40,
    marginLeft:10,
    paddingLeft:20,
    borderColor: '#dddddd',
    borderWidth: 1,
    borderRadius:25,
  },
  SaveButtonStyle: {
    paddingTop:10,
    paddingBottom:10,
    paddingLeft:25,
    paddingRight:25,
    backgroundColor:'#d11c21',
    borderRadius:20,
  },
  whiteTextTitle:{
    color:'#fff',
    textAlign:'center',
  },
  ContinueButtonStyle: {
    paddingTop:12,
    paddingBottom:12,
    backgroundColor:'#d11c21',
    borderRadius:20,
    width:'100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  AddButtonStyle: {
    marginTop:20,
    paddingTop:12,
    paddingBottom:12,
    backgroundColor:'#FFFFFF',
    borderWidth:1,
    borderColor:'#cccccc',
    borderRadius:20,
    width:'100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  AddStepButtonStyle:{
    marginTop:20,
    paddingTop:12,
    paddingBottom:12,
    paddingLeft:40,
    paddingRight:40,
    backgroundColor:'#FFFFFF',
    borderWidth:1,
    borderColor:'#cccccc',
    borderRadius:20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  AddInstructionsButtonStyle: {
    marginTop:15,
    padding:15,
    backgroundColor:'#f7f7f7',
    borderWidth:1,
    borderColor:'#f7f7f7',
    borderRadius:10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight:10,
  },
  AddInstructionsBorderButtonStyle: {
    marginTop:15,
    paddingTop:8,
    paddingBottom:8,
    backgroundColor:'#f7f7f7',
    borderWidth:1,
    borderColor:'#000000',
    borderRadius:10,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft:10,
  },
  formInput: {
    height: 45,
    paddingLeft:30,
    borderColor: '#dddddd',
    borderWidth: 1,
    borderRadius:25,
  },
  profileInput: {
    borderColor: '#dddddd',
    borderWidth: 1,
    borderRadius:20,
    height:40,
    paddingLeft:10,
    width:70,
  },
});

export default styles;
